name:                haskell
version:             0.1.0.0
github:              "jeffhappily/haskell"
license:             BSD3
author:              "jeffhappily"
maintainer:          "goodboy96@live.com.my"
copyright:           "2019 jeffhappily"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/jeffhappily/haskell#readme>

dependencies:
- base >= 4.7 && < 5
- random
- QuickCheck
- containers
- bytestring
- text
- network-uri
- raw-strings-qq
- criterion

library:
  source-dirs: src

